
<div class="container-fluid h-100">
	<div class="row h-100">
    
	    <div class="col-md-6 banner">
	    	<div class="row h-100 align-items-center justify-content-center">
	    		<div class="col-1"></div>
		    	<div class="col-10">
		    		<div>
						<div class="communicationItem">
							<i class="fas fa-search fa-2x me-3"></i>
							Siga o que lhe interessa.
						</div>
						<div class="communicationItem">
							<i class="fas fa-user-friends fa-2x me-3"></i>
							Saiba sobre o que as pessoas estão falando.
						</div>
						<div class="communicationItem">
							<i class="far fa-comment fa-2x me-3"></i>
							Participe da conversa.
						</div>
					</div>
				</div>	
				<div class="col-1"></div>
	    	</div>
	    	
	    </div>

	    <div class="col-md-6 pt-4 pl-5 pr-5">
			<form>
				<div class="row">
					<div class="col">
						<input type="text" class="form-control" placeholder="E-mail">
					</div>
					<div class="col">
						<input type="text" class="form-control" placeholder="Senha">
					</div>
					<div class="col-auto">
						<button type="submit" class="btn btn-primary mb-2">Entrar</button>
					</div>
				</div>
			</form>



			<div class="row pt-5 py-5 pe-5">
				<div class="col ps-5 pe-5">
					<img src="/img/twitter_logo.png" />
					<h1 class="title">Veja o que está acontecendo no mundo agora</h1>

					<h2 class="mt-5 subtitle">Participe hoje do Twitter.</h2>

					<div class="d-grid gap-2">
					  	<a href="/inscreverse" class="btn btn-primary mb-2">Inscrever-se</a>
					</div>			
				</div>	
			</div>
	    </div>

  	</div>
</div>