<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"><?php echo $this->view->info_usuario['username']; ?></span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor"><?php echo $this->view->total_tweets['total_tweets']; ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"><?php echo $this->view->total_seguindo['total_seguindo']; ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"><?php echo $this->view->total_seguidores['total_seguidores']; ?></span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">
					<form method="post" action="/tweet">
						<textarea class="form-control" name="tweet" id="exampleFormControlTextarea1" rows="3"></textarea>
						
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">Tweet</button>
						</div>

					</form>
				</div>
			</div>

			<?php foreach ($this->view->tweets as $id_tweet => $tweet) { ?>
				<div class="row tweet">
					<div class="col">
						<p><strong><?php echo $tweet['username'] ?></strong> <small class="text text-muted">- <?php echo $tweet['tweet_date'] ?></small></p>
						<p><?php echo $tweet['tweet'] ?></p>

						<br />
						<form>
							<?php if($tweet['user_id']==$_SESSION['id']){ ?>
							<div class="col d-flex justify-content-end">
								<a href="<?php echo'/delete_tweet?tweet_id='.$tweet['id']?>" type="submit" class="btn btn-danger"><small>Remover</small></a>
							</div>
						<?php  } ?>
						</form>		
					</div>
				</div>
			<?php } ?>
			
			<div class="row mt-5">
				<nav aria-label="Page navigation example">
				  <ul class="pagination">
				    <li class="page-item">
				      <a class="page-link" href="?pagina=1" aria-label="Previous">
				        <span>Primeira</span>
				      </a>
				    </li>

				    <?php 
				    $pagina = isset($_GET['pagina'])? $_GET['pagina'] : 1; 
				    $total_de_paginas = $this->view->total_de_paginas;
				    $nav_step = 2;
				    $nav_offset = $pagina - $nav_step;
				    $nav_limit = $pagina + $nav_step;




				    if ($pagina - $nav_step < 1){
				    	$nav_offset = 1;
				    	$nav_limit = $nav_step * 2 + 1;

				    	if($nav_limit>$total_de_paginas){
				    		$nav_limit = $total_de_paginas;
				    	}
				    	
				    }
				    if ($pagina + $nav_step > $total_de_paginas){
				    	$nav_limit = $total_de_paginas;
				    	$nav_offset = $total_de_paginas - ($nav_step * 2);

				    	if($nav_offset<1){
				    		$nav_offset = 1;
				    	}
				    	

				    
				    }

				    ?>

				    <?php for($i=$nav_offset; $i <= $nav_limit ; $i++){ ?>
				    	<li class="page-item
				    		<?php 
				    		if($i == $pagina){
				    			echo 'active';
				    		} ?>
				    	">
				    		<a class="page-link" href="?pagina=<?php echo $i?>">
				    		<?php echo $i ?>
				    			
				    		</a>
				    	</li>

				    <?php } ?>
				    
				    
				    <li class="page-item">
				      <a class="page-link" href="?pagina=<?php echo $total_de_paginas ?>" aria-label="Next">
				        <span class="">Última</span>
				      </a>
				    </li>
				  </ul>
				</nav>
			</div>

		</div>


		<div class="col-md-3">
			<?php?>
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="/quem_seguir" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>

	</div>
</div>